#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

npm run check-types || 
(
    echo 'Failed Type check'.
    false;
)

npm run check-format || 
(
    echo 'Failed Styling check'.
    false;
)

npm run check-lint || 
(
    echo 'Failed Lint check'.
    false;
)

echo 'it is ok'

npm run build || 
(
    echo 'Build failed'
    false;
)

echo 'everything is ok'
